// UI
export const APP_LOADED = 'APP_LOADED';
export const SIDE_BAR_OPEN = 'SIDE_BAR_OPEN';
export const SIDE_BAR_CLOSE = 'SIDE_BAR_CLOSE';


// SIGN IN

export const SIGN_IN = 'SIGN_IN';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

// SIGN OUT
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

// ADD FEED
export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';
export const ADD_FEED_FAILURE = 'ADD_FEED_FAILURE';

// SET LATEST
export const SET_LATEST_FEED_SUCCESS = 'SET_LATEST_FEED_SUCCESS';
export const SET_LATEST_FEED_FAILURE = 'SET_LATEST_FEED_FAILURE';

// FETCH FEED ITEMS
export const FETCH_FEED_ITEMS_SUCCESS = 'FETCH_FEED_ITEMS_SUCCESS';
export const FETCH_FEED_ITEMS_FAILURE = 'FETCH_FEED_ITEMS_FAILURE';
// CLEAR FEED ITEMS
export const CLEAR_FEED_ITEMS = 'CLEAR_FEED_ITEMS';

// FETCH FEED LIST
export const FETCH_FEED_LIST_SUCCESS = 'FETCH_FEED_LIST_SUCCESS';
export const FETCH_FEED_LIST_FAILURE = 'FETCH_FEED_LIST_FAILURE';


// DELETE FEEDS
export const DELETE_ALL_FEEDS_SUCCESS = 'DELETE_ALL_FEEDS_SUCCESS';
export const DELETE_ALL_FEEDS_FAILURE = 'DELETE_ALL_FEEDS_FAILURE';

export const DELETE_FEED_FAILURE = 'DELETE_FEED_FAILURE';
export const DELETE_FEED_SUCCESS = 'DELETE_FEED_SUCCESS';

// USER
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';

