
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const ADD_FEED = 'ADD_FEED';
export const REMOVE_FEED = 'REMOVE_FEED';

export const SIDE_BAR_OPEN = 'SIDE_BAR_OPEN';
export const SIDE_BAR_CLOSE = 'SIDE_BAR_CLOSE';

// add feed

export const ADD_FEED_PAGE_LOADED = 'ADD_FEED_PAGE_LOADED';
export const ADD_FEED_PAGE_UNLOADED = 'ADD_FEED_PAGE_UNLOADED';
export const FEED_SUBMITTED = 'FEED_SUBMITTED';
export const LOAD_FEEDS = 'LOAD_FEEDS';

// SIGN IN

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';
export const ADD_FEED_FAILURE = 'ADD_FEED_FAILURE';

export const SET_LATEST_FEED_SUCCESS = 'SET_LATEST_FEED_SUCCESS';
export const SET_LATEST_FEED_FAILURE = 'SET_LATEST_FEED_FAILURE';
export const SET_LATEST_FEED_TO_NULL = 'SET_LATEST_FEED_TO_NULL';

export const FETCH_FEED_ITEMS_SUCCESS = 'FETCH_FEED_ITEMS_SUCCESS';
export const FETCH_FEED_ITEMS_FAILURE = 'FETCH_FEED_ITEMS_FAILURE';

export const FETCH_FEED_LIST_SUCCESS = 'FETCH_FEED_LIST_SUCCESS';
export const FETCH_FEED_LIST_FAILURE = 'FETCH_FEED_LIST_FAILURE';

export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';

export const INIT_AUTH = 'INIT_AUTH';

export const AUTH_SIGNED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS,';

export const DELETE_ALL_FEEDS_SUCCESS = 'DELETE_ALL_FEEDS_SUCCESS';
export const DELETE_ALL_FEEDS_FAILURE = 'DELETE_ALL_FEEDS_FAILURE';

export const DELETE_FEEDS_SUCCESS = 'DELETE_FEEDS_SUCCESS';
export const DELETE_FEEDS_FAILURE = 'DELETE_FEEDS_FAILURE';

export const DELETE_FEED_FAILURE = 'DELETE_FEED_FAILURE';
export const DELETE_FEED_SUCCESS = 'DELETE_FEED_SUCCESS';
